name:       educational-prelude
version:    0.1.0.0
github:     "imesense/educational-prelude"
license:    MIT
author:     "Renat Shakirov"
maintainer: "acidicmercury8@outlook.com"
copyright:  "2022 (c) Renat Shakirov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/educational-prelude#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src/EducationalPrelude

executables:
  educational-prelude-exe:
    main: Main.hs
    source-dirs: src/EducationalPrelude.Demo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - educational-prelude

tests:
  educational-prelude-test:
    main: Spec.hs
    source-dirs: test/EducationalPrelude.Tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - educational-prelude
